name: Run Pytest

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest geopandas geopy tqdm

    - name: Install pyisd
      run: |
        pip install .
    - name: Run Pytest
      run: |
        pytest tests/test_isd_lite.py
