name: Run Pytest

on:
  workflow_dispatch: # Déclencheur manuel
  pull_request: # Déclencheur lors d'une pull request vers la branche principale
    branches:
      - main
  schedule: # Déclencheur programmé
    - cron: "0 8 * * 1" # Chaque lundi à 8h00 UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest geopandas geopy tqdm

    - name: Install pyisd
      run: |
        pip install .
    - name: Run Pytest
      run: |
        pytest tests/test_isd_lite.py
